apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop
  labels:
    app: workshop
spec:
  selector:
    matchLabels:
      app: workshop
  template:
    metadata: 
      labels:
        app: workshop
    spec:
      containers:
      - name: tom-cont
        image: nandana237/tom_img:latest
        ports:
        - containerPort: 8080
  replicas: 10
