apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  labels:
    app: prod
spec:
  selector:
    matchLabels:
      app: prod
  template:
    metadata: 
      labels:
        app: prod
    spec:
      containers:
      - name: tom-cont
        image: nandana237/reg-img:latest
        ports:
        - containerPort: 8080
  replicas: 20
