apiVersion: v1
kind: Services
metadata:
  name: my-apache-service
spec:
  type: LoadBalancer
  ports: 
  - name: my-apache-port
    port: 8080
    targetPort: 80
  selector:
    app: my-apache-service
